version: "3.8"

services:
  backend:
    container_name: paapo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - MJ_APIKEY_PUBLIC=${MJ_APIKEY_PUBLIC}
      - MJ_APIKEY_PRIVATE=${MJ_APIKEY_PRIVATE}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    restart: always
    networks:
      - paapo-network

  db:
    image: postgres:15
    container_name: paapo-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paapo-network

volumes:
  postgres_data:

networks:
  paapo-network:
    driver: bridge