spring.application.name=projeto-paapo
string.datasource.url=jdbc:postgresql://${db-host}:${db-port}/${db-database}
spring.datasource.username=${db-username}
spring.datasource.password=${db-password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=${jwt-secret}
app.jwt.expiration=86400000
app.jwt.header=Authorization
app.jwt.prefix=Bearer